export const FETCH_COMPETITION_REQUEST = 'FETCH_COMPETITION_REQUEST';
export const FETCH_COMPETITION_SUCCESS = 'FETCH_COMPETITION_SUCCESS';
export const FETCH_COMPETITION_FAILURE = 'FETCH_COMPETITION_FAILURE';
